#!/usr/bin/bash
clear
sudo apt update
sudo apt full-upgrade -y
sudo apt -y install python3 python3-full python3-pip snapd
sudo systemctl start snapd ; sudo systemctl start snapd.apparmor
sudo systemctl enable snapd ; sudo systemctl enable snapd.apparmor
sudo snap install metasploit-framework
python3 -m pip install colorama
mkdir ./RAT/
mkdir ./DAT/
chmod 777 ./client.py
chmod 777 ./server.py
clear
echo -e "\e[36mAnonXploit\e[0m \e[1;92minstalled\e[0m\e[97m!\e[0m"
echo -e "\033[31mEnjoy the tool\033[0m \033[1;31mwithout\033[0m \033[31mworrying about \033[1;31mantivirus\033[0m.\033[0m"
echo
